### ISSUE TITLE
using as cmake

### ISSUE THREAD

**Issue by jaychanda** [vpetrigo/caches#13]
how to add this cache library using cmake so that i can use like this 
#include <lru_cache_policy.hpp>
#include <cache.hpp>

**Comment by vpetrigo** [comment]
Hello @jaychanda,

Let's consider you have the following project structure
```
project_name\
    main.c
    CMakeLists.txt
```

If you want the cache library to be included as a git submodule then you may do the following:
```bash
$ git submodule init https://github.com/vpetrigo/caches.git
```

That will result in the following structure:
```
project_name\
    cache\
    main.c
    CMakeLists.txt
```

Then you should add the following into your `CMakeLists.txt`:
```cmake
include_directories(${CMAKE_CURRENT_LIST_DIR}/cache/include)
```

OR you may add cache's directory as following and use internally set up variable `CACHE_INCLUDE_DIRS`:
```cmake
add_subdirectory(cache/)

include_directories(${CACHE_INCLUDE_DIRS})
```

Hope this helps you.
