### ISSUE TITLE
small edit in the readme example

### ISSUE THREAD

**Issue by shokrof** [vpetrigo/caches#15]
name space should be added to this line
`using lru_cache_t = typename caches::fixed_sized_cache<Key, Value, LRUCachePolicy<Key>>;`

to be 
`using lru_cache_t = typename caches::fixed_sized_cache<Key, Value, caches::LRUCachePolicy<Key>>;`

have a good day

**Comment by vpetrigo** [comment]
Hey, thank you for reporting!
