### ISSUE TITLE
It works for iOS and Android?

### ISSUE THREAD

**Issue by paulocoutinhox** [vpetrigo/caches#29]
Hi,

It works for iOS and Android?

thanks.

**Comment by vpetrigo** [comment]
It should work on Android as NDK uses `libc++` . Regarding iOS I have no idea as Swift does not allow calling C++ functions. Most likely you need to provide Objective-C++ wrappers to existing API.

**Comment by vpetrigo** [comment]
Feel free to reopen this issue if you come up with other questions/proposals. 😄
