### ISSUE TITLE
`std::unordered_set` does not have a function named `crbegin`

### ISSUE THREAD

**Issue by innomentats** [vpetrigo/caches#4]
code is here: https://github.com/vpetrigo/caches/blob/master/include/cache_policy.hpp#L43

According to http://en.cppreference.com/w/cpp/container/unordered_set, `unordered_set` does not have that function. It is `unordered` :P

**Comment by vpetrigo** [comment]
Yep, it must be a typo. I will fix that.

**Comment by vpetrigo** [comment]
@innomentats Now it's fixed. Thanks for your notes!
